# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 03:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20170730_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
