# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-16 23:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20170801_2033'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpvoteModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.CommentModel')),
            ],
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='caption',
            field=models.CharField(default='', max_length=240),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='image',
            field=models.FileField(default='', upload_to='user_images'),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='image_url',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.UserModel'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='upvotemodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.UserModel'),
        ),
    ]
