# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-18 04:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_auto_20170817_1257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upvotemodel',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='upvotemodel',
            name='post',
        ),
        migrations.RemoveField(
            model_name='upvotemodel',
            name='user',
        ),
        migrations.AddField(
            model_name='commentmodel',
            name='upvote_number',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.DeleteModel(
            name='UpvoteModel',
        ),
    ]
