# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-18 04:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_auto_20170817_2135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentmodel',
            name='upvote_number',
        ),
    ]
