# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-18 04:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_remove_commentmodel_upvote_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentmodel',
            name='upvote_number',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
