# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-18 05:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_commentmodel_upvote_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentmodel',
            name='upvote_number',
            field=models.IntegerField(default=0),
        ),
    ]
